-- 20230427_add_survey_columns_to_attendance.sql

ALTER TABLE "Attendance"
  ADD COLUMN "survey_submitted_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN "q1" INTEGER CHECK ("q1" BETWEEN 1 AND 5),
  ADD COLUMN "q2" INTEGER CHECK ("q2" BETWEEN 1 AND 5),
  ADD COLUMN "q3" INTEGER CHECK ("q3" BETWEEN 1 AND 5),
  ADD COLUMN "q4" INTEGER CHECK ("q4" BETWEEN 1 AND 5),
  ADD COLUMN "q5" INTEGER CHECK ("q5" BETWEEN 1 AND 5),
  ADD COLUMN "q6" TEXT;
